# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21d8ac622ce1ffcc08d89687fa6bce77"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "tender-dev"
handle = "tender-dev"

[build]
dev_store_url = "whitefox-sandbox-checkout-extensibility.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/api/auth"]

[pos]
embedded = false
