# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21d8ac622ce1ffcc08d89687fa6bce77"
name = "tender-dev"
handle = "tender-dev"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "whitefox-sandbox-checkout-extensibility.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
