# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-04"

[[extensions]]
name = "market-messaging"
handle = "market-messaging"
type = "ui_extension"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/MMBanner.jsx"
target = "purchase.checkout.block.render"
[[extensions.targeting]]
module = "./src/MMImage.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
[[extensions.settings.fields]]
key = "text"
type = "rich_text_field"
name = "Message"
[[extensions.settings.fields]]
key = "status"
type = "single_line_text_field"
name = "Status"
description = "info, warning, success, critical"

[[extensions.settings.fields]]
key = "image_url_d"
type = "single_line_text_field"
name = "Desktop: Image URL"
[[extensions.settings.fields]]
key = "image_url_m"
type = "single_line_text_field"
name = "Mobile: Image URL"
[[extensions.settings.fields]]
key = "alt"
type = "single_line_text_field"
name = "Accessibility description"

[[extensions.settings.fields]]
key = "show_markets"
type = "single_line_text_field"
name = "Do show on these markets:"
description = "Only applies if not blank"
[[extensions.settings.fields]]
key = "hide_markets"
type = "single_line_text_field"
name = "Don't show on these markets:"

