api_version = "2024-10"

[[extensions]]
name = "Address Validation"
handle = "address-validation"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.delivery-address.render-before"

[extensions.capabilities]
api_access = true
block_progress = true