api_version = "2024-10"

[[extensions]]
name = "Address Validation"
handle = "address-validation"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true